-- MySQL Script generated by MySQL Workbench
-- 10/23/15 13:03:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema portal_empleo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema portal_empleo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portal_empleo` DEFAULT CHARACTER SET latin1 ;
USE `portal_empleo` ;

-- -----------------------------------------------------
-- Table `portal_empleo`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal_empleo`.`tipo_usuario` (
  `Id_tipo_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo_usuario` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id_tipo_usuario`),
  UNIQUE INDEX `tipo_usuario` (`tipo_usuario` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `portal_empleo`.`domicilio_empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal_empleo`.`domicilio_empresa` (
  `Id_domicilio_empresa` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  PRIMARY KEY (`Id_domicilio_empresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal_empleo`.`responsable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal_empleo`.`responsable` (
  `Id_responsable` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  `puesto` VARCHAR(45) NULL,
  PRIMARY KEY (`Id_responsable`),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal_empleo`.`info_basica_e`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal_empleo`.`info_basica_e` (
  `Id_info_basica_e` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  `giro` VARCHAR(100) NULL,
  `razon_social` VARCHAR(100) NULL,
  `fundacion` DATE NULL,
  `Id_domicilio_empresa` INT NOT NULL,
  `Id_responsable` INT NOT NULL,
  PRIMARY KEY (`Id_info_basica_e`),
  INDEX `fk_info_basica_e_domicilio_empresa1_idx` (`Id_domicilio_empresa` ASC),
  INDEX `fk_info_basica_e_responsable1_idx` (`Id_responsable` ASC),
  CONSTRAINT `fk_info_basica_e_domicilio_empresa1`
    FOREIGN KEY (`Id_domicilio_empresa`)
    REFERENCES `portal_empleo`.`domicilio_empresa` (`Id_domicilio_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_info_basica_e_responsable1`
    FOREIGN KEY (`Id_responsable`)
    REFERENCES `portal_empleo`.`responsable` (`Id_responsable`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal_empleo`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal_empleo`.`empresa` (
  `Id_empresa` INT NOT NULL AUTO_INCREMENT,
  `logotipo` VARCHAR(45) NULL,
  `Id_info_basica_e` INT NOT NULL,
  PRIMARY KEY (`Id_empresa`),
  INDEX `fk_empresa_info_basica_e1_idx` (`Id_info_basica_e` ASC),
  CONSTRAINT `fk_empresa_info_basica_e1`
    FOREIGN KEY (`Id_info_basica_e`)
    REFERENCES `portal_empleo`.`info_basica_e` (`Id_info_basica_e`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal_empleo`.`documentacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal_empleo`.`documentacion` (
  `Id_documentacion` INT NOT NULL AUTO_INCREMENT,
  `curp` TINYINT(1) NULL,
  `afore` TINYINT(1) NULL,
  `rfc` TINYINT(1) NULL,
  `seguro_social` TINYINT(1) NULL,
  `cartilla_militar` TINYINT(1) NULL,
  `pasaporte` TINYINT(1) NULL,
  `extranjero_documento` VARCHAR(45) NULL,
  `licencia` TINYINT(1) NULL,
  `clase_numero_licencia` VARCHAR(45) NULL,
  PRIMARY KEY (`Id_documentacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal_empleo`.`domicilio_persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal_empleo`.`domicilio_persona` (
  `Id_domicilio_persona` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NULL,
  `direccion` VARCHAR(100) NULL,
  `colonia` VARCHAR(45) NULL,
  `cp` VARCHAR(45) NULL,
  PRIMARY KEY (`Id_domicilio_persona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal_empleo`.`datos_personales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal_empleo`.`datos_personales` (
  `Id_datos_personales` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido_materno` VARCHAR(45) NULL,
  `apellido_paterno` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  `genero` ENUM('M', 'F') NULL,
  `edad` INT NULL,
  `nacionalidad` ENUM('Mexicana', 'Extranjera') NULL,
  `estado_civil` ENUM('Soltero', 'Divorciado', 'Casado', 'Viudo') NULL,
  `Id_domicilio_persona` INT NOT NULL,
  PRIMARY KEY (`Id_datos_personales`),
  INDEX `fk_datos_personales_domicilio_persona1_idx` (`Id_domicilio_persona` ASC),
  CONSTRAINT `fk_datos_personales_domicilio_persona1`
    FOREIGN KEY (`Id_domicilio_persona`)
    REFERENCES `portal_empleo`.`domicilio_persona` (`Id_domicilio_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal_empleo`.`datos_generales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal_empleo`.`datos_generales` (
  `Id_datos_generales` INT NOT NULL AUTO_INCREMENT,
  `afiliado` TINYINT(1) NULL,
  `afianzado` TINYINT(1) NULL,
  `seguro_vida` TINYINT(1) NULL,
  `viajar` TINYINT(1) NULL,
  `cambiar_residencia` TINYINT(1) NULL,
  `fecha_empezar` DATE NULL,
  PRIMARY KEY (`Id_datos_generales`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal_empleo`.`economia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal_empleo`.`economia` (
  `Id_economia` INT NOT NULL AUTO_INCREMENT,
  `ingresos` TINYINT(1) NULL,
  `conyuge_trabaja` TINYINT(1) NULL,
  `casa_propia` TINYINT(1) NULL,
  `renta` TINYINT(1) NULL,
  `vehiculo_propio` ENUM('Automovil', 'Motocicleta', 'No') NULL,
  `deudas` TINYINT(1) NULL,
  PRIMARY KEY (`Id_economia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal_empleo`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal_empleo`.`persona` (
  `Id_persona` INT NOT NULL AUTO_INCREMENT,
  `fotografia` VARCHAR(45) NULL,
  `Id_documentacion` INT NOT NULL,
  `Id_datos_personales` INT NOT NULL,
  `Id_datos_generales` INT NOT NULL,
  `Id_economia` INT NOT NULL,
  PRIMARY KEY (`Id_persona`),
  INDEX `fk_persona_documentacion1_idx` (`Id_documentacion` ASC),
  INDEX `fk_persona_datos_personales1_idx` (`Id_datos_personales` ASC),
  INDEX `fk_persona_datos_generales1_idx` (`Id_datos_generales` ASC),
  INDEX `fk_persona_economia1_idx` (`Id_economia` ASC),
  CONSTRAINT `fk_persona_documentacion1`
    FOREIGN KEY (`Id_documentacion`)
    REFERENCES `portal_empleo`.`documentacion` (`Id_documentacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_persona_datos_personales1`
    FOREIGN KEY (`Id_datos_personales`)
    REFERENCES `portal_empleo`.`datos_personales` (`Id_datos_personales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_persona_datos_generales1`
    FOREIGN KEY (`Id_datos_generales`)
    REFERENCES `portal_empleo`.`datos_generales` (`Id_datos_generales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_persona_economia1`
    FOREIGN KEY (`Id_economia`)
    REFERENCES `portal_empleo`.`economia` (`Id_economia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal_empleo`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal_empleo`.`login` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) CHARACTER SET 'latin1' COLLATE 'latin1_spanish_ci' NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `Id_tipo_usuario` INT(11) NOT NULL,
  `Id_empresa` INT NULL,
  `Id_persona` INT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `username` (`username` ASC),
  INDEX `fk_login_tipo_usuario_idx` (`Id_tipo_usuario` ASC),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC),
  INDEX `fk_login_empresa1_idx` (`Id_empresa` ASC),
  INDEX `fk_login_persona1_idx` (`Id_persona` ASC),
  CONSTRAINT `fk_login_tipo_usuario`
    FOREIGN KEY (`Id_tipo_usuario`)
    REFERENCES `portal_empleo`.`tipo_usuario` (`Id_tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_login_empresa1`
    FOREIGN KEY (`Id_empresa`)
    REFERENCES `portal_empleo`.`empresa` (`Id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_login_persona1`
    FOREIGN KEY (`Id_persona`)
    REFERENCES `portal_empleo`.`persona` (`Id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `portal_empleo`.`vacantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal_empleo`.`vacantes` (
  `Id_vacantes` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `puesto` VARCHAR(45) NULL,
  `horario` VARCHAR(45) NULL,
  `sueldo` INT NULL,
  `descripcion` VARCHAR(250) NULL,
  `estatus` TINYINT(1) NULL,
  `Id_empresa` INT NOT NULL,
  PRIMARY KEY (`Id_vacantes`),
  INDEX `fk_vacantes_empresa1_idx` (`Id_empresa` ASC),
  CONSTRAINT `fk_vacantes_empresa1`
    FOREIGN KEY (`Id_empresa`)
    REFERENCES `portal_empleo`.`empresa` (`Id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal_empleo`.`documentos_extra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal_empleo`.`documentos_extra` (
  `Id_documento_extra` INT NOT NULL,
  `documento` VARCHAR(45) NULL,
  `Id_persona` INT NOT NULL,
  PRIMARY KEY (`Id_documento_extra`),
  INDEX `fk_documentos_extra_persona1_idx` (`Id_persona` ASC),
  CONSTRAINT `fk_documentos_extra_persona1`
    FOREIGN KEY (`Id_persona`)
    REFERENCES `portal_empleo`.`persona` (`Id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal_empleo`.`estudios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal_empleo`.`estudios` (
  `Id_estudio` INT NOT NULL AUTO_INCREMENT,
  `nivel` ENUM('Primaria', 'Secundaria', 'Preparatoria', 'Universidad', 'Maestria', 'Posgrado', 'Doctorado') NULL,
  `nombre` VARCHAR(45) NULL,
  `titulo` VARCHAR(45) NULL,
  `años` INT NULL,
  `Id_persona` INT NOT NULL,
  PRIMARY KEY (`Id_estudio`),
  INDEX `fk_estudios_persona1_idx` (`Id_persona` ASC),
  CONSTRAINT `fk_estudios_persona1`
    FOREIGN KEY (`Id_persona`)
    REFERENCES `portal_empleo`.`persona` (`Id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal_empleo`.`jefes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal_empleo`.`jefes` (
  `Id_jefe` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `comentarios` VARCHAR(250) NULL,
  PRIMARY KEY (`Id_jefe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal_empleo`.`referencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal_empleo`.`referencias` (
  `Id_referencia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `direccion` VARCHAR(200) NULL,
  `numero` VARCHAR(45) NULL,
  `parentesco` VARCHAR(45) NULL,
  `Id_persona` INT NOT NULL,
  PRIMARY KEY (`Id_referencia`),
  INDEX `fk_referencias_persona1_idx` (`Id_persona` ASC),
  CONSTRAINT `fk_referencias_persona1`
    FOREIGN KEY (`Id_persona`)
    REFERENCES `portal_empleo`.`persona` (`Id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal_empleo`.`trabajos_anteriores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal_empleo`.`trabajos_anteriores` (
  `Id_trabajo_anterior` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `años` INT NULL,
  `direccion` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  `puesto` VARCHAR(45) NULL,
  `sueldo` INT NULL,
  `motivo_separacion` VARCHAR(240) NULL,
  `Id_jefe` INT NOT NULL,
  `Id_persona` INT NOT NULL,
  PRIMARY KEY (`Id_trabajo_anterior`),
  INDEX `fk_trabajos_anteriores_persona1_idx` (`Id_persona` ASC),
  INDEX `fk_trabajos_anteriores_jefes1_idx` (`Id_jefe` ASC),
  CONSTRAINT `fk_trabajos_anteriores_persona1`
    FOREIGN KEY (`Id_persona`)
    REFERENCES `portal_empleo`.`persona` (`Id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trabajos_anteriores_jefes1`
    FOREIGN KEY (`Id_jefe`)
    REFERENCES `portal_empleo`.`jefes` (`Id_jefe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal_empleo`.`notificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal_empleo`.`notificaciones` (
  `Id_notificacion` INT NOT NULL AUTO_INCREMENT,
  `Id_empresa` INT NOT NULL,
  `Id_persona` INT NOT NULL,
  PRIMARY KEY (`Id_notificacion`, `Id_empresa`, `Id_persona`),
  INDEX `fk_empresa_has_persona_persona1_idx` (`Id_persona` ASC),
  INDEX `fk_empresa_has_persona_empresa1_idx` (`Id_empresa` ASC),
  CONSTRAINT `fk_empresa_has_persona_empresa1`
    FOREIGN KEY (`Id_empresa`)
    REFERENCES `portal_empleo`.`empresa` (`Id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empresa_has_persona_persona1`
    FOREIGN KEY (`Id_persona`)
    REFERENCES `portal_empleo`.`persona` (`Id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
